apiVersion: v1
kind: Secret
metadata:
  name: mysql-info
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  MYSQL_SERVER_IP: {{ .Values.mysql.host | toString | b64enc | quote }}
  MYSQL_SERVER_PORT: {{ .Values.mysql.port | toString | b64enc | quote }}
  MYSQL_USERNAME: {{ .Values.mysql.username | toString | b64enc | quote }}
  MYSQL_PWD: {{ .Values.mysql.password | toString | b64enc | quote }}