apiVersion: v1
kind: Secret
metadata:
  name: nacos-info
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  NACOS_SERVER_IP: {{ .Values.nacos.host | toString | b64enc | quote }}
  NACOS_SERVER_PORT: {{ .Values.nacos.port | toString | b64enc | quote }}
  NACOS_USERNAME: {{ .Values.nacos.username | toString | b64enc | quote }}
  NACOS_PWD: {{ .Values.nacos.password | toString | b64enc | quote }}
  NACOS_NAMESPACE: {{ .Values.nacos.namespace | toString | b64enc | quote }}
  NACOS_GROUP: {{ .Values.nacos.group | toString | b64enc | quote }}
  NACOS_CLUSTER_NAME: {{ .Values.nacos.cluster | toString | b64enc | quote }}