{{- if .Values.configmaps }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-import-configmaps"
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      serviceAccountName: {{ .Release.Name }}-import-configmaps-sa
      restartPolicy: Never
      containers:
      - name: import-configmaps
        image: "{{ include "configmaps.image" . }}"
        imagePullPolicy: {{ .Values.configmaps.image.pullPolicy | quote }}
        command:
        - /bin/sh
        - -c
        - |
          bash <<'EOF'
          set -ex
          kubectl apply --server-side -f /configmaps/ --force-conflicts
          EOF
{{- end -}}