apiVersion: v2
appVersion: 1.2.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
  - name: upm-ui
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-ui
    version: 1.1.0
    alias: ui
  - name: upm-gateway-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-gateway-ms
    version: 1.1.0
    alias: gateway
  - name: upm-auth-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-auth-ms
    version: 1.1.0
    alias: auth
  - name: upm-user-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      -  upm-user-ms
    version: 1.1.0
    alias: user
  - name: upm-resource-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-resource-ms
    version: 1.1.0
    alias: resource
  - name: upm-operatelog-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-operatelog-ms
    version: 1.1.0
    alias: operatelog
  - name: upm-service-es-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-service-es-ms
    version: 1.1.0
    alias: service-elasticsearch
    condition: upm.elasticsearch.enabled
  - name: upm-service-kafka-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-service-kafka-ms
    version: 1.1.0
    alias: service-kafka
    condition: upm.kafka.enabled
  - name: upm-service-zookeeper-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-service-zookeeper-ms
    version: 1.1.0
    alias: service-zookeeper
    condition: upm.zookeeper.enabled
  - name: upm-service-mysql-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-service-mysql-ms
    version: 1.1.0
    alias: service-mysql
    condition: upm.mysql.enabled
  - name: upm-service-redis-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-service-redis-ms
    version: 1.1.0
    alias: service-redis
    condition: upm.redis.enabled
  - name: upm-service-redis-cluster-ms
    repository: https://upmio.github.io/helm-charts
    tags:
      - upm-service-redis-cluster-ms
    version: 1.1.0
    alias: service-redis-cluster
    condition: upm.redis-cluster.enabled
  - name: helix
    repository: https://upmio.github.io/helm-charts
    tags:
      - helix
    version: 1.1.1
    alias: helix
name: upm-platform
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.1
description: Chart for upm platform
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
