global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

unit-operator:
  crds:
    enabled: true
  image:
    registry: quay.io
    tag: v1.2.3
  nodeAffinityPreset:
    type: "hard"
    key: "upm.engine.node"
    values:
      - "enable"

compose-operator:
  crds:
    enabled: true
  image:
    registry: quay.io
    tag: v1.2.3
  nodeAffinityPreset:
    type: "hard"
    key: "upm.engine.node"
    values:
      - "enable"

configmaps:
  enabled: true
  image:
    # Repository for container
    registry: quay.io
    repository: upmio/upm-template
    tag: v1.2.3
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets (secrets must be manually created in the namespace)
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## Example:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    # - name: regcred
    pullSecrets: []